// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRKpao8o30aEaMni3SIDPgunwXbSvORcY',
    appId: '1:964752564154:web:f172bdef95a20bf1be4783',
    messagingSenderId: '964752564154',
    projectId: 'saitama-4134e',
    authDomain: 'saitama-4134e.firebaseapp.com',
    databaseURL: 'https://saitama-4134e-default-rtdb.firebaseio.com',
    storageBucket: 'saitama-4134e.firebasestorage.app',
    measurementId: 'G-L447TEZJ64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWJleGAkfCK8nS5GhS04McFHqKUzxoKqw',
    appId: '1:964752564154:android:ebb05ec1ef89b6f2be4783',
    messagingSenderId: '964752564154',
    projectId: 'saitama-4134e',
    databaseURL: 'https://saitama-4134e-default-rtdb.firebaseio.com',
    storageBucket: 'saitama-4134e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw3U1huJnOu3PECBFDhLfhE7ns-XCfHu0',
    appId: '1:964752564154:ios:46fb70cbffad1f41be4783',
    messagingSenderId: '964752564154',
    projectId: 'saitama-4134e',
    databaseURL: 'https://saitama-4134e-default-rtdb.firebaseio.com',
    storageBucket: 'saitama-4134e.firebasestorage.app',
    androidClientId: '964752564154-obdjk5ueh8kmt6icvt1pep5svf254906.apps.googleusercontent.com',
    iosClientId: '964752564154-855udm1nf4ets7d9ktlfq498fvilveiq.apps.googleusercontent.com',
    iosBundleId: 'com.mg61.lifehero',
  );
}
